@echo off
title START ALL 100 INSTANCES
echo Starting 100 voting instances...
echo This will open 100 terminal windows!
echo.
pause
start cmd /k loop_voter_1.bat
start cmd /k loop_voter_2.bat
start cmd /k loop_voter_3.bat
start cmd /k loop_voter_4.bat
start cmd /k loop_voter_5.bat
start cmd /k loop_voter_6.bat
start cmd /k loop_voter_7.bat
start cmd /k loop_voter_8.bat
start cmd /k loop_voter_9.bat
start cmd /k loop_voter_10.bat
start cmd /k loop_voter_11.bat
start cmd /k loop_voter_12.bat
start cmd /k loop_voter_13.bat
start cmd /k loop_voter_14.bat
start cmd /k loop_voter_15.bat
start cmd /k loop_voter_16.bat
start cmd /k loop_voter_17.bat
start cmd /k loop_voter_18.bat
start cmd /k loop_voter_19.bat
start cmd /k loop_voter_20.bat
start cmd /k loop_voter_21.bat
start cmd /k loop_voter_22.bat
start cmd /k loop_voter_23.bat
start cmd /k loop_voter_24.bat
start cmd /k loop_voter_25.bat
start cmd /k loop_voter_26.bat
start cmd /k loop_voter_27.bat
start cmd /k loop_voter_28.bat
start cmd /k loop_voter_29.bat
start cmd /k loop_voter_30.bat
start cmd /k loop_voter_31.bat
start cmd /k loop_voter_32.bat
start cmd /k loop_voter_33.bat
start cmd /k loop_voter_34.bat
start cmd /k loop_voter_35.bat
start cmd /k loop_voter_36.bat
start cmd /k loop_voter_37.bat
start cmd /k loop_voter_38.bat
start cmd /k loop_voter_39.bat
start cmd /k loop_voter_40.bat
start cmd /k loop_voter_41.bat
start cmd /k loop_voter_42.bat
start cmd /k loop_voter_43.bat
start cmd /k loop_voter_44.bat
start cmd /k loop_voter_45.bat
start cmd /k loop_voter_46.bat
start cmd /k loop_voter_47.bat
start cmd /k loop_voter_48.bat
start cmd /k loop_voter_49.bat
start cmd /k loop_voter_50.bat
start cmd /k loop_voter_51.bat
start cmd /k loop_voter_52.bat
start cmd /k loop_voter_53.bat
start cmd /k loop_voter_54.bat
start cmd /k loop_voter_55.bat
start cmd /k loop_voter_56.bat
start cmd /k loop_voter_57.bat
start cmd /k loop_voter_58.bat
start cmd /k loop_voter_59.bat
start cmd /k loop_voter_60.bat
start cmd /k loop_voter_61.bat
start cmd /k loop_voter_62.bat
start cmd /k loop_voter_63.bat
start cmd /k loop_voter_64.bat
start cmd /k loop_voter_65.bat
start cmd /k loop_voter_66.bat
start cmd /k loop_voter_67.bat
start cmd /k loop_voter_68.bat
start cmd /k loop_voter_69.bat
start cmd /k loop_voter_70.bat
start cmd /k loop_voter_71.bat
start cmd /k loop_voter_72.bat
start cmd /k loop_voter_73.bat
start cmd /k loop_voter_74.bat
start cmd /k loop_voter_75.bat
start cmd /k loop_voter_76.bat
start cmd /k loop_voter_77.bat
start cmd /k loop_voter_78.bat
start cmd /k loop_voter_79.bat
start cmd /k loop_voter_80.bat
start cmd /k loop_voter_81.bat
start cmd /k loop_voter_82.bat
start cmd /k loop_voter_83.bat
start cmd /k loop_voter_84.bat
start cmd /k loop_voter_85.bat
start cmd /k loop_voter_86.bat
start cmd /k loop_voter_87.bat
start cmd /k loop_voter_88.bat
start cmd /k loop_voter_89.bat
start cmd /k loop_voter_90.bat
start cmd /k loop_voter_91.bat
start cmd /k loop_voter_92.bat
start cmd /k loop_voter_93.bat
start cmd /k loop_voter_94.bat
start cmd /k loop_voter_95.bat
start cmd /k loop_voter_96.bat
start cmd /k loop_voter_97.bat
start cmd /k loop_voter_98.bat
start cmd /k loop_voter_99.bat
start cmd /k loop_voter_100.bat
